#include "KeysMapping.hpp"

#include <rfb/keysym.h>

rfbKeySym SDLKeySymToRfbKeySym(SDL_Keycode sym) {
    switch (sym) {
        case SDLK_BACKSPACE:
            return XK_BackSpace;
        case SDLK_TAB:
            return XK_Tab;
        case SDLK_CLEAR:
            return XK_Clear;
        case SDLK_RETURN:
            return XK_Return;
        case SDLK_PAUSE:
            return XK_Pause;
        case SDLK_ESCAPE:
            return XK_Escape;
        case SDLK_DELETE:
            return XK_Delete;
        case SDLK_KP_0:
            return XK_KP_0;
        case SDLK_KP_1:
            return XK_KP_1;
        case SDLK_KP_2:
            return XK_KP_2;
        case SDLK_KP_3:
            return XK_KP_3;
        case SDLK_KP_4:
            return XK_KP_4;
        case SDLK_KP_5:
            return XK_KP_5;
        case SDLK_KP_6:
            return XK_KP_6;
        case SDLK_KP_7:
            return XK_KP_7;
        case SDLK_KP_8:
            return XK_KP_8;
        case SDLK_KP_9:
            return XK_KP_9;
        case SDLK_KP_PERIOD:
            return XK_KP_Decimal;
        case SDLK_KP_DIVIDE:
            return XK_KP_Divide;
        case SDLK_KP_MULTIPLY:
            return XK_KP_Multiply;
        case SDLK_KP_MINUS:
            return XK_KP_Subtract;
        case SDLK_KP_PLUS:
            return XK_KP_Add;
        case SDLK_KP_ENTER:
            return XK_KP_Enter;
        case SDLK_KP_EQUALS:
            return XK_KP_Equal;
        case SDLK_UP:
            return XK_Up;
        case SDLK_DOWN:
            return XK_Down;
        case SDLK_RIGHT:
            return XK_Right;
        case SDLK_LEFT:
            return XK_Left;
        case SDLK_INSERT:
            return XK_Insert;
        case SDLK_HOME:
            return XK_Home;
        case SDLK_END:
            return XK_End;
        case SDLK_PAGEUP:
            return XK_Page_Up;
        case SDLK_PAGEDOWN:
            return XK_Page_Down;
        case SDLK_F1:
            return XK_F1;
        case SDLK_F2:
            return XK_F2;
        case SDLK_F3:
            return XK_F3;
        case SDLK_F4:
            return XK_F4;
        case SDLK_F5:
            return XK_F5;
        case SDLK_F6:
            return XK_F6;
        case SDLK_F7:
            return XK_F7;
        case SDLK_F8:
            return XK_F8;
        case SDLK_F9:
            return XK_F9;
        case SDLK_F10:
            return XK_F10;
        case SDLK_F11:
            return XK_F11;
        case SDLK_F12:
            return XK_F12;
        case SDLK_F13:
            return XK_F13;
        case SDLK_F14:
            return XK_F14;
        case SDLK_F15:
            return XK_F15;
        case SDLK_NUMLOCKCLEAR:
            return XK_Num_Lock;
        case SDLK_CAPSLOCK:
            return XK_Caps_Lock;
        case SDLK_SCROLLLOCK:
            return XK_Scroll_Lock;
        case SDLK_RSHIFT:
            return XK_Shift_R;
        case SDLK_LSHIFT:
            return XK_Shift_L;
        case SDLK_RCTRL:
            return XK_Control_R;
        case SDLK_LCTRL:
            return XK_Control_L;
        case SDLK_RALT:
            return XK_Alt_R;
        case SDLK_LALT:
            return XK_Alt_L;
        case SDLK_LGUI:
            return XK_Super_L;
        case SDLK_RGUI:
            return XK_Super_R;
        case SDLK_MODE:
            return XK_Mode_switch;
        case SDLK_HELP:
            return XK_Help;
        case SDLK_PRINTSCREEN:
            return XK_Print;
        case SDLK_SYSREQ:
            return XK_Sys_Req;
        default:
            return static_cast<rfbKeySym>(sym);
    }
}
